apiVersion: v2
name: mca-devops-app
description: A Helm chart for MCA DevOps Test N-tier application
type: application
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: postgresql
    version: 12.x.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled