# Global configuration
global:
  imageRegistry: ""
  imagePullSecrets: []

# Backend configuration
backend:
  replicaCount: 2
  image:
    repository: localhost:52156/mca-backend
    tag: "latest"
    pullPolicy: IfNotPresent
  
  service:
    type: ClusterIP
    port: 8080
    targetPort: 8080
    
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
      
# Frontend configuration
frontend:
  replicaCount: 2
  image:
    repository: localhost:52156/mca-backend
    tag: "latest"
    pullPolicy: IfNotPresent
    
  service:
    type: ClusterIP
    port: 80
    targetPort: 80
    
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Database configuration
database:
  # External database connection
  external:
    enabled: true
    host: "my-db-test.io"
    port: 5432
    database: "postgres"
    username: "myapplication"
    password: "M3P@ssw0rd!"
    
# PostgreSQL subchart (for local development)
postgresql:
  enabled: false  # Use external by default
  auth:
    postgresPassword: "postgres"
    username: "myapplication"
    password: "M3P@ssw0rd!"
    database: "mca_db"

# Ingress configuration
ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: mca-app.local
      paths:
        - path: /
          pathType: Prefix
          service: mca-frontend
        - path: /api
          pathType: Prefix
          service: mca-backend
  tls: []
