apiVersion: v1
kind: Service
metadata:
  name: {{ include "mca-devops-app.fullname" . }}-backend
  labels:
    {{- include "mca-devops-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "mca-devops-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
