apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mca-devops-app.fullname" . }}-db-secret
  labels:
    {{- include "mca-devops-app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.database.external.enabled }}
  username: {{ .Values.database.external.username | b64enc }}
  password: {{ .Values.database.external.password | b64enc }}
  {{- else }}
  username: {{ .Values.postgresql.auth.username | b64enc }}
  password: {{ .Values.postgresql.auth.password | b64enc }}
  {{- end }}
